SUBURBS = [
    "Abbotsford",
    "Aberfeldie",
    "Airport West",
    "Albanvale",
    "Albert Park",
    "Albion",
    "Alphington",
    "Altona",
    "Altona Meadows",
    "Altona North",
    "Ardeer",
    "Armadale",
    "Ascot Vale",
    "Ashburton",
    "Ashwood",
    "Aspendale",
    "Aspendale Gardens",
    "Attwood",
    "Avondale Heights",
    "Balaclava",
    "Balwyn",
    "Balwyn North",
    "Bayswater",
    "Beaumaris",
    "Bellfield",
    "Bentleigh",
    "Bentleigh East",
    "Black Rock",
    "Blackburn",
    "Blackburn North",
    "Blackburn South",
    "Bonbeach",
    "Boronia",
    "Box Hill",
    "Box Hill North",
    "Box Hill South",
    "Braybrook",
    "Briar Hill",
    "Brighton",
    "Brighton East",
    "Brunswick",
    "Brunswick East",
    "Brunswick West",
    "Bulleen",
    "Burnley",
    "Burwood",
    "Burwood East",
    "Camberwell",
    "Canterbury",
    "Carlton",
    "Carlton North",
    "Carnegie",
    "Carrum",
    "Chadstone",
    "Cheltenham",
    "Clifton Hill",
    "Coburg",
    "Coburg North",
    "Collingwood",
    "Coolaroo",
    "Craigieburn",
    "Cremorne",
    "Croydon",
    "Dallas",
    "Deepdene",
    "Delahey",
    "Derrimut",
    "Diamond Creek",
    "Dingley Village",
    "Docklands",
    "Doncaster",
    "Doncaster East",
    "Donvale",
    "Eaglemont",
    "East Melbourne",
    "Elsternwick",
    "Eltham",
    "Elwood",
    "Essendon",
    "Essendon North",
    "Essendon West",
    "Eumemmerring",
    "Fairfield",
    "Fawkner",
    "Fitzroy",
    "Fitzroy North",
    "Flemington",
    "Footscray",
    "Forest Hill",
    "Gardenvale",
    "Glen Huntly",
    "Glen Iris",
    "Glenroy",
    "Greensborough",
    "Hadfield",
    "Hampton",
    "Hampton East",
    "Hawthorn",
    "Hawthorn East",
    "Heidelberg",
    "Heidelberg Heights",
    "Heidelberg West",
    "Highett",
    "Hillside",
    "Hoppers Crossing",
    "Hughesdale",
    "Ivanhoe",
    "Ivanhoe East",
    "Jacana",
    "Kealba",
    "Keilor",
    "Keilor Downs",
    "Keilor East",
    "Keilor Lodge",
    "Keilor Park",
    "Kensington",
    "Kew",
    "Kew East",
    "Kingsbury",
    "Kingsville",
    "Kooyong",
    "Lalor",
    "Lower Plenty",
    "Maidstone",
    "Malvern",
    "Malvern East",
    "Maribyrnong",
    "Mckinnon",
    "Meadow Heights",
    "Melbourne",
    "Middle Park",
    "Mill Park",
    "Mitcham",
    "Mont Albert",
    "Montmorency",
    "Moonee Ponds",
    "Moorabbin",
    "Mordialloc",
    "Mount Waverley",
    "Mulgrave",
    "Murrumbeena",
    "Newport",
    "Niddrie",
    "North Melbourne",
    "Northcote",
    "Nunawading",
    "Oak Park",
    "Oakleigh",
    "Oakleigh East",
    "Oakleigh South",
    "Ormond",
    "Parkville",
    "Pascoe Vale",
    "Point Cook",
    "Port Melbourne",
    "Preston",
    "Princes Hill",
    "Reservoir",
    "Richmond",
    "Ringwood",
    "Rosanna",
    "Roxburgh Park",
    "Sandringham",
    "Seabrook",
    "Seddon",
    "South Melbourne",
    "South Yarra",
    "St Albans",
    "St Kilda",
    "St Kilda East",
    "Strathmore",
    "Sunbury",
    "Sunshine",
    "Sunshine North",
    "Sunshine West",
    "Surrey Hills",
    "Sydenham",
    "Tarneit",
    "Taylors Hill",
    "Templestowe",
    "Templestowe Lower",
    "Thomastown",
    "Thornbury",
    "Toorak",
    "Truganina",
    "Tullamarine",
    "Vermont",
    "Vermont South",
    "Viewbank",
    "Wantirna",
    "Wantirna South",
    "Werribee",
    "West Footscray",
    "West Melbourne",
    "Williamstown",
    "Williamstown North",
    "Windsor",
    "Yarraville"
]
